name: Checks

on:
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  static-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x  # Specify the Python version you want to use

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff black mypy check-manifest isort

      - name: Lint Code (ruff)
        if: true
        run: ruff check .

      - name: Format Code (black)
        if: true
        run: black --check --diff .

      - name: Sort imports (isort)
        if: true
        run: isort . --profile black --check --diff

      - name: Type Check (mypy)
        if: true
        run: mypy src tests
        continue-on-error: true

      - name: Check Manifest (check-manifest)
        if: true
        run: check-manifest

      - name: Use Codecov to track coverage
        if: true
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.xml   # coverage report

  pytest:
    if: success() || failure()
    needs: static-checks
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11"]  # Add the Python versions you want to test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install pytest

      - name: Run Tests and Calculate Coverage
        run: pytest
